# Generated by Django 3.2.3 on 2024-11-20 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoriterecipe',
            options={'default_related_name': 'favorites', 'ordering': ('-recipe__created_at',), 'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранное'},
        ),
        migrations.AlterModelOptions(
            name='import',
            options={'ordering': ('-date_added',), 'verbose_name': 'Учет импорта CSV', 'verbose_name_plural': 'Учет импорта CSV'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'default_related_name': 'recipes', 'ordering': ('-created_at',), 'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'default_related_name': 'recipe_ingredients', 'ordering': ('ingredient',), 'verbose_name': 'Ингредиент', 'verbose_name_plural': 'Ингредиенты'},
        ),
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'default_related_name': 'shopping_cart', 'ordering': ('-recipe__created_at',), 'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзина'},
        ),
    ]
