# Generated by Django 3.2.3 on 2024-11-20 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20241120_0846'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'default_related_name': 'subscribers', 'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['first_name']},
        ),
    ]
